services:
  # Backend API Service
  - type: web
    name: apsar-tracker-backend
    env: node
    plan: free
    rootDir: ./backend
    buildCommand: npm ci --omit=dev || npm install --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: apsar-mongodb
    plan: free
